CREATE TABLE CUSTOMERS(
    id SERIAL PRIMARY KEY, name CHARACTER VARYING(100),
    surname CHARACTER VARYING(100),
    age INTEGER, phone_number BIGINT
    );

CREATE TABLE ORDERS(
    id SERIAL PRIMARY KEY,
    date DATE,
    customer_id INTEGER REFERENCES CUSTOMERS (id),
    product_name CHARACTER VARYING(100),
    amount BIGINT
    );